server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.circuitbreaker: DEBUG
