spring:
  application:
    name: notification-service

  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092
        - localhost:9094
      # key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: user-create-delete-events

  mail:
    host: smtp.mail.ru
    port: 587
    username: itclasszoom25@mail.ru
    password: mxZQYGWuS6O4i4nMgSBG
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

kafka:
  topics:
    user-events: user-create-delete-events-topic

mail:
  from:
    address: itclasszoom25@mail.ru

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 0
