spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/task4_spring_boot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    producer:
      bootstrap-servers: kafka-1:9090,kafka-2:9090,kafka-3:9090
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      # retries: 10
      # properties:
      #   retry.backoff.ms: 1000
      properties:
        delivery.timeout.ms: 10000
        linger.ms: 0
        request.timeout.ms: 5000
        enable.idempotence: true
        max.in.flight.request.per.connection: 5

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

server:
  port: 0
